# Generated by Django 5.0.6 on 2024-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
